# Building configuration parameters
building:
  state: "AL"
  county: "Pike"
  building_type: "SmallHotel"
  building_id: "example_building"
  area: 500
  num_floors: 1
  height: null
  n_buildings: 1
  n_weather_files: 2
  weather: "example_weather.epw"
  weather_validation: null 