algorithm: "ppo"
policy_type: "MlpPolicy"
device: "cpu"  # Set cpu if no cnn
n_steps: 2048
batch_size: 64
gamma: 0.99
learning_rate: 0.0003
clip_range: 0.2
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
gae_lambda: 0.95
verbose: 1