type: unitary_g36
heating_setpoint_c: 20.0
cooling_setpoint_c: 22.0
kp: 3.1803
ki: 0.020905
min_fan_fraction: 0.8257
med_fan_fraction: 0.9785
sat_min_c: 17.21
sat_max_c: null
availability_on: 2.0
target_schedule:
  enabled: false
