# Main configuration file for Building2Building project
defaults:
  - fetch_building: office_vermont

# Basic configuration
seed: 42
track: true

# Directories  
base_dir: results

# Hydra settings
hydra:
  run:
    dir: ${base_dir}/${name}_${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: false 