# @package _global_
name: fetch_buildings

building:
  state: "VT"
  county: "Orleans" 
  building_type: "SmallOffice"
  area: 1000                    
  num_floors: 1            
  height: 10.0              
  n_buildings: 4              
  n_weather_files: 2          
  keep_original: true