total_timesteps: 20000000
eval_freq: 200000
eval_episodes: 1
num_train_envs: 10
cb_gradient_save_freq: 500

# Optional: Number of timesteps to include in trajectory snippet logged after each PPO update
# trajectory_snippet_length: 10
