
defaults:
  - _self_
  - wandb: default
  - training: default
  - policy: ppo
  - reward: deadband
  - rollout: default

env:
  normalize_obs: true
  hvac_action_space: box
  n_bins_continuous: 21
  control_mode: sensible_load

n_episodes: 1

seed: 42



