defaults:
  - _self_
  - bldg: single_family
  - policy: unitary_g36
  - reward: deadband
  - wandb: default

hydra:
  run:
    dir: outputs/${policy.type}/${now:%d-%m-%Y}/${now:%H-%M-%S}

env:
  normalize_obs: false
  max_steps: 35040

n_episodes: 1
