
defaults:
  - _self_
  - wandb: default
  - training: default
  - policy: sac
  - reward: deadband

env:
  normalize_obs: true

n_episodes: 1

seed: 42

# Sweep configuration
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      seed: 1,2,3,4,5
      policy.learning_rate: 0.0001,0.0003,0.001
      reward.energy_weight: 0.0,0.5,1.0,5.0


