defaults:
  - _self_
  - bldg: multi_zone
  - wandb: default
  - training: default
  - policy: ppo
  - reward: deadband
  - task: default

env:
  normalize_obs: true
  normalize_action: true
  max_steps: 105120             # full year at 5-min timesteps (365 * 24 * 12)

seed: 42

hydra:
  run:
    dir: outputs/train_multizones/${bldg.building_type}/${bldg.split}_${bldg.index}/${policy.algorithm}/${now:%Y%m%d_%H%M%S}
  job:
    chdir: true
