# @package _global_
# PPO Training configuration

policy_type: ppo

training:
  total_timesteps: 175200
  save_model: true

ppo:
  learning_rate: 0.0003
  num_envs: 1
  num_steps: 2048
  anneal_lr: true
  gamma: 0.99
  gae_lambda: 0.95
  num_minibatches: 32
  update_epochs: 10
  norm_adv: true
  clip_coef: 0.2
  clip_vloss: true
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  target_kl: null
  eval_frequency: 8760 