#!/usr/bin/env python3
"""Full-year rollout + analysis for a single building with tuned reactive controllers.

Produces three artifacts per building, all written under ``--output-dir``:

* ``<building_id>_cz<cz>.npz`` — per-step zone temperatures, setpoints, outdoor
  temperature, energy, actions, rewards, and reward decomposition
  (``temp_term``, ``energy_term``).  Schema matches the pre-existing
  ``analysis/officemedium_tuned/`` artifacts so downstream tooling keeps working.
* ``<building_id>_cz<cz>_analysis.png`` — 4-panel summary figure:
  zone temps vs per-zone setpoints, outdoor dry-bulb, HVAC energy,
  and reward decomposition over the year.
* ``<building_id>_cz<cz>.report.json`` — per-zone and aggregate deviation
  statistics; individual files are merged into a building-type-level
  ``report.json`` by ``baselines.summarize_tuned_analysis``.

Usage::

    python -m baselines.analyze_tuned_controller \\
        --building-type OfficeMedium --building-id OfficeMedium-4949 \\
        --climate-zone 1 --task task1 \\
        --output-dir analysis/officemedium_tuned_v2
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

import matplotlib.pyplot as plt
import numpy as np
import yaml

import building2building as b2b
from baselines.controllers.air_loop import AirLoopConfig, AirLoopPolicy
from baselines.controllers.unitary_hvac import UnitaryHvacConfig, UnitaryHvacPolicy

logger = logging.getLogger("analyze_tuned_controller")

VAV_BUILDING_TYPES = {"OfficeMedium"}
TUNED_CONFIGS_DIR = Path(__file__).parent / "configs" / "tuned_controllers"


def select_test_buildings(
    building_type: str, climate_zone: int, n: int, *, split: str = "test"
) -> list[str]:
    """Pick the first ``n`` test-split buildings for ``(building_type, climate_zone)``.

    For building types without an ASHRAE climate-zone assignment (e.g.
    ``SingleFamilyHouse``), the CZ filter is skipped and the first ``n``
    IDs are returned as-is.  Ordering follows ``list_buildings`` /
    ``list_buildings_by_climate_zone`` (deterministic metadata order) to
    keep runs reproducible across SLURM attempts.
    """
    if building_type in b2b.TYPES_WITHOUT_CLIMATE_ZONE:
        return b2b.list_buildings(building_type, split=split)[:n]
    matching = b2b.list_buildings_by_climate_zone(
        building_type, climate_zone, split=split
    )
    if len(matching) < n:
        logger.warning(
            "Only %d test buildings match %s / cz=%d (wanted %d) — returning what we have",
            len(matching),
            building_type,
            climate_zone,
            n,
        )
    return matching[:n]


@dataclass
class RolloutArtifacts:
    """In-memory form of everything saved to disk per building."""

    zone_temperatures: np.ndarray  # (T, n_zones)
    zone_names: list[str]
    outdoor_temperature: np.ndarray  # (T,)
    energy_electricity: np.ndarray  # (T,)
    energy_gas: np.ndarray  # (T,)
    actions: np.ndarray  # (T-1, n_act)
    action_names: list[str]
    rewards: np.ndarray  # (T-1,)
    temp_term: np.ndarray  # (T-1,) MSE across controlled zones
    energy_term: np.ndarray  # (T-1,) electricity + gas
    setpoints: np.ndarray  # (T, n_zones) per-zone target
    controlled_zones: list[str]
    building_type: str
    building_id: str
    climate_zone: int
    task: str


# ---------------------------------------------------------------------------
# Config loading (handles SFH cz0 quirk that run_reactive_control skips)
# ---------------------------------------------------------------------------


def _load_tuned_config(
    bt: str, cz: int, *, task: str
) -> UnitaryHvacConfig | AirLoopConfig:
    """Load a tuned controller config from disk.

    Mirrors the naming convention used after the 2026-04-20 re-tune:
    ``{air_loop|unitary_hvac}_{building_type_lower}_cz{cz}.yaml``.
    The ``_task1`` segment from the raw tuner output has been stripped
    when the configs were copied into the repo.
    """
    is_vav = bt in VAV_BUILDING_TYPES
    prefix = "air_loop" if is_vav else "unitary_hvac"
    path = TUNED_CONFIGS_DIR / f"{prefix}_{bt.lower()}_cz{cz}.yaml"
    if not path.exists():
        logger.warning(
            "No tuned config at %s — falling back to default %s",
            path,
            "AirLoopConfig" if is_vav else "UnitaryHvacConfig",
        )
        return AirLoopConfig() if is_vav else UnitaryHvacConfig()

    # ``yaml.unsafe_load`` tolerates the ``!!python/tuple`` tags that the
    # tuner's ``yaml.dump`` emits for ``weekend_days`` inside
    # ``target_schedule`` (the tuner should really use ``safe_dump`` — tracked
    # separately).  Safe here because these files are generated by our own
    # tuning pipeline.
    raw = yaml.unsafe_load(path.read_text())
    raw.pop("type", None)
    raw.pop("target_schedule", None)
    # Coerce int-as-float scalars the same way run_reactive_control does.
    coerced = {
        k: (float(v) if isinstance(v, (int, float)) and not isinstance(v, bool) else v)
        for k, v in raw.items()
    }
    return AirLoopConfig(**coerced) if is_vav else UnitaryHvacConfig(**coerced)


def _select_policy(bt: str, cz: int, task: str, env: Any):
    cfg = _load_tuned_config(bt, cz, task=task)
    if bt in VAV_BUILDING_TYPES:
        policy = AirLoopPolicy(cfg)  # type: ignore[arg-type]
    else:
        policy = UnitaryHvacPolicy(cfg)  # type: ignore[arg-type]
    policy.bind_env(env)
    return policy


# ---------------------------------------------------------------------------
# Observation parsing
# ---------------------------------------------------------------------------


def _find_index(obs_names: list[str], needle: str) -> int | None:
    for i, n in enumerate(obs_names):
        if n.strip().lower() == needle.strip().lower():
            return i
    return None


def _zone_temp_indices(obs_names: list[str]) -> tuple[list[int], list[str]]:
    indices: list[int] = []
    labels: list[str] = []
    prefix = "zone air temperature"
    for i, n in enumerate(obs_names):
        s = n.strip()
        if s.lower().startswith(prefix):
            indices.append(i)
            labels.append(s[len("ZONE AIR TEMPERATURE") :].strip() or f"zone_{i}")
    return indices, labels


def _setpoint_indices(obs_names: list[str]) -> tuple[list[int], list[str]]:
    """Return indices and zone-name labels for per-zone target setpoints.

    The observation naming convention is ``target_temperature <zone>``.
    """
    indices: list[int] = []
    labels: list[str] = []
    prefix = "target_temperature"
    for i, n in enumerate(obs_names):
        s = n.strip()
        if s.lower().startswith(prefix):
            indices.append(i)
            labels.append(s[len("target_temperature") :].strip() or f"setpoint_{i}")
    return indices, labels


def _extract_energy_series(
    observations: np.ndarray, obs_names: list[str]
) -> tuple[np.ndarray, np.ndarray]:
    e_idx = _find_index(obs_names, "energy_electricity")
    g_idx = _find_index(obs_names, "energy_gas")
    T = observations.shape[0]
    elec = (
        observations[:, e_idx].astype(np.float32)
        if e_idx is not None
        else np.zeros(T, np.float32)
    )
    gas = (
        observations[:, g_idx].astype(np.float32)
        if g_idx is not None
        else np.zeros(T, np.float32)
    )
    return elec, gas


# ---------------------------------------------------------------------------
# Stats / reward decomposition
# ---------------------------------------------------------------------------


def _compute_deviation_stats(
    zone_temps: np.ndarray, setpoints: np.ndarray, deadband_c: float = 1.0
) -> dict[str, float]:
    """Zone-temperature deviation statistics over the episode.

    Positive deviation = zone is warmer than setpoint (overshoot → overcooling
    demand in summer, over-heating in winter).  ``frac_in_deadband`` uses a
    symmetric ``|T − setpoint| ≤ deadband_c`` window.
    """
    dev = zone_temps - setpoints
    abs_dev = np.abs(dev)
    return {
        "mean_dev_c": float(dev.mean()),
        "std_dev_c": float(dev.std()),
        "pct_1": float(np.percentile(dev, 1)),
        "pct_5": float(np.percentile(dev, 5)),
        "pct_25": float(np.percentile(dev, 25)),
        "pct_50": float(np.percentile(dev, 50)),
        "pct_75": float(np.percentile(dev, 75)),
        "pct_95": float(np.percentile(dev, 95)),
        "pct_99": float(np.percentile(dev, 99)),
        "frac_in_deadband": float((abs_dev <= deadband_c).mean()),
        "frac_above_deadband": float((dev > deadband_c).mean()),
        "frac_below_deadband": float((dev < -deadband_c).mean()),
        "max_over_c": float(dev.max()),
        "max_under_c": float((-dev).max()),
    }


def _decompose_reward(
    zone_temps_controlled: np.ndarray,  # (T, n_controlled)
    setpoints_controlled: np.ndarray,  # (T, n_controlled)
    energy_elec: np.ndarray,  # (T,)
    energy_gas: np.ndarray,  # (T,)
) -> tuple[np.ndarray, np.ndarray]:
    """Reconstruct reward decomposition used by :func:`base_reward_function`.

    The live reward is ``-(MSE(zone − target) + energy_weight · (elec + gas))``.
    We return the two additive terms separately so the plot can show which one
    drives the loss over the year.  The terms are evaluated at post-step obs
    (i.e. length T, where T = episode_length + 1).  Callers downstream slice
    them to ``T-1`` to line up with actions/rewards.
    """
    temp_term = ((zone_temps_controlled - setpoints_controlled) ** 2).mean(axis=1)
    energy_term = energy_elec + energy_gas
    return temp_term.astype(np.float32), energy_term.astype(np.float32)


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------


def _make_analysis_figure(art: RolloutArtifacts, deadband_c: float = 1.0) -> plt.Figure:
    T = art.zone_temperatures.shape[0]
    hours = np.arange(T) / 6.0  # 10-min env timestep → hours

    fig, axes = plt.subplots(4, 1, figsize=(13, 14), sharex=True)
    title = (
        f"{art.building_type} / {art.building_id} / cz{art.climate_zone} / {art.task}"
    )
    fig.suptitle(title, fontsize=11)

    # Panel 1: zone temperatures vs setpoints (only controlled zones for clarity).
    ax = axes[0]
    cmap = plt.get_cmap("tab10")
    controlled_set = set(art.controlled_zones)
    visible_cols = [j for j, z in enumerate(art.zone_names) if z in controlled_set]
    if not visible_cols:
        visible_cols = list(range(min(len(art.zone_names), 10)))
    for k, j in enumerate(visible_cols):
        c = cmap(k % 10)
        ax.plot(
            hours, art.zone_temperatures[:, j], color=c, lw=0.5, label=art.zone_names[j]
        )
        ax.plot(hours, art.setpoints[:, j], color=c, lw=0.4, ls="--", alpha=0.6)
    ax.set_ylabel("Temp (°C)")
    ax.set_title("Zone temperature (solid) vs per-zone setpoint (dashed)")
    ax.legend(loc="upper left", bbox_to_anchor=(1.01, 1.0), fontsize=7)

    # Panel 2: deviation from setpoint with deadband shading.
    ax = axes[1]
    if visible_cols:
        dev = art.zone_temperatures[:, visible_cols] - art.setpoints[:, visible_cols]
        for k, j in enumerate(visible_cols):
            ax.plot(hours, dev[:, k], color=cmap(k % 10), lw=0.5)
        ax.axhspan(
            -deadband_c,
            deadband_c,
            color="green",
            alpha=0.1,
            label=f"±{deadband_c}°C deadband",
        )
        ax.axhline(0, color="black", lw=0.4, alpha=0.6)
    ax.set_ylabel("T − setpoint (°C)")
    ax.set_title("Deviation from setpoint (controlled zones)")
    ax.legend(loc="upper right", fontsize=8)

    # Panel 3: outdoor temperature + HVAC energy.
    ax = axes[2]
    ax.plot(
        hours, art.outdoor_temperature, color="gray", lw=0.4, label="Outdoor T (°C)"
    )
    ax.set_ylabel("Outdoor T (°C)")
    ax.legend(loc="upper left", fontsize=8)
    ax_en = ax.twinx()
    ax_en.plot(
        hours,
        art.energy_electricity,
        color="tab:red",
        lw=0.4,
        label="Electricity",
        alpha=0.7,
    )
    ax_en.plot(
        hours, art.energy_gas, color="tab:blue", lw=0.4, label="Natural gas", alpha=0.7
    )
    ax_en.set_ylabel("Energy (Wh/m²)")
    ax_en.legend(loc="upper right", fontsize=8)

    # Panel 4: reward decomposition.
    ax = axes[3]
    Ta = art.temp_term.shape[0]
    hrs_a = np.arange(Ta) / 6.0
    ax.plot(hrs_a, -art.temp_term, color="tab:orange", lw=0.4, label="−MSE(T−target)")
    ax.plot(hrs_a, -art.energy_term, color="tab:purple", lw=0.4, label="−(elec + gas)")
    ax.plot(hrs_a, art.rewards, color="black", lw=0.4, label="Total reward")
    ax.axhline(0, color="black", lw=0.4, alpha=0.3)
    ax.set_ylabel("Reward components")
    ax.set_xlabel("Time (hours)")
    ax.set_title("Reward decomposition (negative = penalty)")
    ax.legend(loc="lower left", fontsize=8)

    fig.tight_layout(rect=[0, 0, 0.85, 0.97])
    return fig


# ---------------------------------------------------------------------------
# Main rollout
# ---------------------------------------------------------------------------


def rollout_and_analyze(
    building_type: str,
    building_id: str,
    climate_zone: int,
    task: str,
    run_period: Literal["full_year", "winter", "summer"] = "full_year",
) -> RolloutArtifacts:
    env = b2b.make_env(
        building_type,
        building_id=building_id,
        task=task,
        run_period=run_period,
    )
    try:
        obs_names: list[str] = env.metadata["observation_names"]
        act_names: list[str] = env.metadata["action_names"]
        # ``morphology.controlled_zones`` is populated by build_morphology.
        morphology = env.metadata.get("morphology")
        controlled_zones: list[str] = []
        if morphology is not None and hasattr(morphology, "controlled_zones"):
            controlled_zones = list(morphology.controlled_zones)  # type: ignore[arg-type]
        elif morphology is not None and hasattr(morphology, "nodes"):
            for node in morphology.nodes:
                nid = getattr(node, "id", "")
                if nid.startswith("zone:"):
                    controlled_zones.append(nid[len("zone:") :])

        logger.info(
            "Rollout: %s / %s (cz=%d, task=%s) — zones=%d, run_period=%s",
            building_type,
            building_id,
            climate_zone,
            task,
            len(controlled_zones),
            run_period,
        )
        policy = _select_policy(building_type, climate_zone, task, env)

        def _controller(obs: np.ndarray) -> np.ndarray:
            action, _ = policy.predict(obs, deterministic=True)
            return action

        traj = b2b.rollout(env, _controller)
        observations = traj.observations
        rewards = traj.rewards
        actions = traj.actions
    finally:
        env.close()

    zone_indices, zone_labels = _zone_temp_indices(obs_names)
    sp_indices, sp_labels = _setpoint_indices(obs_names)
    out_t_idx = _find_index(obs_names, "outdoor_temperature")

    zone_temps = (
        observations[:, zone_indices].astype(np.float32)
        if zone_indices
        else np.zeros((observations.shape[0], 0), np.float32)
    )
    # Align setpoint columns to zone order by name.
    sp_by_zone = {label: i for i, label in zip(sp_indices, sp_labels)}
    aligned_sp_cols = []
    for zl in zone_labels:
        if zl in sp_by_zone:
            aligned_sp_cols.append(observations[:, sp_by_zone[zl]])
        else:
            aligned_sp_cols.append(np.full(observations.shape[0], np.nan, np.float32))
    setpoints = np.stack(aligned_sp_cols, axis=1).astype(np.float32)

    outdoor = (
        observations[:, out_t_idx].astype(np.float32)
        if out_t_idx is not None
        else np.zeros(observations.shape[0], np.float32)
    )
    elec, gas = _extract_energy_series(observations, obs_names)

    controlled_cols = [
        j for j, zl in enumerate(zone_labels) if zl in set(controlled_zones)
    ]
    if controlled_cols:
        zc = zone_temps[:, controlled_cols]
        sc = setpoints[:, controlled_cols]
    else:
        zc = zone_temps
        sc = setpoints

    # Fill NaN setpoints (zones without an explicit target) with their zone
    # temperature so the MSE contribution is zero.
    mask = np.isnan(sc)
    if mask.any():
        sc = np.where(mask, zc, sc)

    temp_term_full, energy_term_full = _decompose_reward(zc, sc, elec, gas)
    # Reward applies to post-step state → slice to align with actions.
    temp_term = temp_term_full[1:]
    energy_term = energy_term_full[1:]

    return RolloutArtifacts(
        zone_temperatures=zone_temps,
        zone_names=zone_labels,
        outdoor_temperature=outdoor,
        energy_electricity=elec,
        energy_gas=gas,
        actions=actions.astype(np.float32),
        action_names=act_names,
        rewards=rewards.astype(np.float32),
        temp_term=temp_term,
        energy_term=energy_term,
        setpoints=setpoints,
        controlled_zones=controlled_zones,
        building_type=building_type,
        building_id=building_id,
        climate_zone=climate_zone,
        task=task,
    )


def save_artifacts(
    art: RolloutArtifacts, output_dir: Path, deadband_c: float = 1.0
) -> dict[str, Any]:
    output_dir.mkdir(parents=True, exist_ok=True)
    stem = f"{art.building_id}_cz{art.climate_zone}"
    npz_path = output_dir / f"{stem}.npz"
    png_path = output_dir / f"{stem}_analysis.png"
    json_path = output_dir / f"{stem}.report.json"

    meta_dict = {
        "building_type": art.building_type,
        "building_id": art.building_id,
        "climate_zone": art.climate_zone,
        "task": art.task,
        "zone_names": art.zone_names,
        "controlled_zones": art.controlled_zones,
        "action_names": art.action_names,
    }
    np.savez_compressed(
        npz_path,
        zone_temperatures=art.zone_temperatures,
        outdoor_temperature=art.outdoor_temperature,
        energy_electricity=art.energy_electricity,
        energy_gas=art.energy_gas,
        actions=art.actions,
        rewards=art.rewards,
        temp_term=art.temp_term,
        energy_term=art.energy_term,
        setpoints=art.setpoints,
        meta=np.array(json.dumps(meta_dict)),
    )
    logger.info("Saved trajectory → %s", npz_path)

    fig = _make_analysis_figure(art, deadband_c=deadband_c)
    fig.savefig(png_path, dpi=110, bbox_inches="tight")
    plt.close(fig)
    logger.info("Saved figure → %s", png_path)

    # Per-zone + aggregate deviation stats (only for controlled zones, matching
    # the existing report schema).
    controlled_set = set(art.controlled_zones)
    per_zone: list[dict[str, Any]] = []
    controlled_cols: list[int] = []
    for j, zl in enumerate(art.zone_names):
        if zl in controlled_set or not art.controlled_zones:
            sp_col = art.setpoints[:, j]
            if np.isnan(sp_col).all():
                continue
            stats = _compute_deviation_stats(
                art.zone_temperatures[:, j],
                np.where(np.isnan(sp_col), art.zone_temperatures[:, j], sp_col),
                deadband_c,
            )
            per_zone.append({"zone": zl, **stats})
            controlled_cols.append(j)

    if controlled_cols:
        z_ctrl = art.zone_temperatures[:, controlled_cols]
        s_ctrl = art.setpoints[:, controlled_cols]
        mask = np.isnan(s_ctrl)
        s_ctrl = np.where(mask, z_ctrl, s_ctrl)
        aggregate = _compute_deviation_stats(z_ctrl.ravel(), s_ctrl.ravel(), deadband_c)
    else:
        aggregate = {}

    actuator_stats = {
        "n_actuators": int(art.actions.shape[1]) if art.actions.ndim == 2 else 0,
        "mean": (
            [float(x) for x in art.actions.mean(axis=0)] if art.actions.size else []
        ),
        "frac_at_min": (
            [
                float(x)
                for x in (art.actions <= art.actions.min(axis=0) + 1e-6).mean(axis=0)
            ]
            if art.actions.size
            else []
        ),
        "frac_at_max": (
            [
                float(x)
                for x in (art.actions >= art.actions.max(axis=0) - 1e-6).mean(axis=0)
            ]
            if art.actions.size
            else []
        ),
    }
    report: dict[str, Any] = {
        "building_type": art.building_type,
        "building_id": art.building_id,
        "climate_zone": art.climate_zone,
        "task": art.task,
        "episode_length": int(art.rewards.shape[0]),
        "temperatures": {"per_zone": per_zone, "aggregate": aggregate},
        "actions": actuator_stats,
        "reward": {
            "total": float(art.rewards.sum()),
            "mean_per_step": float(art.rewards.mean()),
            "temp_term_mean": float(art.temp_term.mean()),
            "energy_term_mean": float(art.energy_term.mean()),
        },
    }
    json_path.write_text(json.dumps(report, indent=2))
    logger.info("Saved report → %s", json_path)
    return report


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("--building-type", required=True)
    p.add_argument(
        "--building-id",
        default=None,
        help="Explicit building ID.  Omit together with --n-buildings to auto-select.",
    )
    p.add_argument("--climate-zone", type=int, required=True)
    p.add_argument(
        "--n-buildings",
        type=int,
        default=1,
        help="When --building-id is absent, analyze this many test-split buildings "
        "matching (--building-type, --climate-zone).",
    )
    p.add_argument("--task", default="task1")
    p.add_argument(
        "--run-period", default="full_year", choices=["full_year", "winter", "summer"]
    )
    p.add_argument(
        "--base-dir",
        type=Path,
        default=Path(os.environ.get("SCRATCH", "outputs")),
        help="Root directory; results go under <base_dir>/b2b/analysis/tuned_controllers/",
    )
    p.add_argument("--output-dir", required=False, default=None, type=Path)
    p.add_argument(
        "--deadband-c",
        type=float,
        default=1.0,
        help="Deadband half-width for satisfaction stats.",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(name)s %(levelname)s: %(message)s"
    )
    args = parse_args(argv)

    output_dir = (
        args.output_dir
        if args.output_dir is not None
        else args.base_dir / "b2b" / "analysis" / "tuned_controllers"
    )

    if args.building_id is not None:
        building_ids = [args.building_id]
    else:
        building_ids = select_test_buildings(
            args.building_type, args.climate_zone, args.n_buildings
        )
        if not building_ids:
            logger.error(
                "No test buildings found for %s / cz=%d",
                args.building_type,
                args.climate_zone,
            )
            sys.exit(1)
        logger.info(
            "Auto-selected %d buildings for %s cz=%d: %s",
            len(building_ids),
            args.building_type,
            args.climate_zone,
            building_ids,
        )

    for bid in building_ids:
        try:
            art = rollout_and_analyze(
                args.building_type,
                bid,
                args.climate_zone,
                args.task,
                run_period=args.run_period,
            )
            save_artifacts(art, output_dir, deadband_c=args.deadband_c)
        except Exception:
            logger.exception(
                "Rollout failed: %s / %s cz=%d",
                args.building_type,
                bid,
                args.climate_zone,
            )


if __name__ == "__main__":
    main()
